### ISSUE TITLE
Microsoft's Motives

### ISSUE THREAD

**Issue by bderiso** [bderiso/Microsoft-Github-acquisition#1]
A common critique of Microsoft is that their past actions indications indicate:
* At best: a lack of respect for open-source ideals.
* At worst: actual hostility and a desire to undermine and destroy open-source initiatives.

Microsoft has traditionally been a "software" company, and so their motivation is to sell their software at the expense of any competitors, even going so far as to pressure them out of business.

# Counterpoint
With new ownership and company missions, today Microsoft is much more of a "hosting & Services" company. For example, Azure & Office 365 are their main products, with the Windows operating system being a large but legacy offering.

**Comment by bderiso** [comment]
(Thanks to [immexerxez's comment here](https://github.com/upend/IF_MS_BUYS_GITHUB_IMMA_OUT/issues/13#issuecomment-394341504) for inspiring this post.)

**Comment by bderiso** [comment]
User differentsmoke has [coincidentally expressed many of the counter-points here.](https://github.com/upend/IF_MS_BUYS_GITHUB_IMMA_OUT/issues/13#issuecomment-394351074)

**Comment by bderiso** [comment]
Here is a good discussion on the in & outs of this issue in general: https://news.ycombinator.com/item?id=17221527

**Comment by aethelwulffe** [comment]
The day I can take a hard drive image with a licensed copy of Windows, chock full of configured and licensed software and stick in into a different machine (even if I have to pay a fee) to upgrade or replace hardware without fearing I can't re-install some other software license (and I don't mean Windows Story junk) or have to spend days trying to get everything re-configured is the day I will start thinking that MS has changed.

**Comment by bderiso** [comment]
[Copying from another thread:](https://github.com/bderiso/Microsoft-Github-acquisition/issues/3#issuecomment-394715205)

# @marcus-sa:
"Taken directly from their blog post https://blogs.microsoft.com/blog/2018/06/04/microsoft-github-empowering-developers
Clearly it's all just part of a big marketing strategy.

Given all of this, together with GitHub, we see three clear opportunities ahead.

First, we will empower developers at every stage of the development lifecycle – from ideation to collaboration to deployment to the cloud. Going forward, GitHub will remain an open platform, which any developer can plug into and extend. Developers will continue to be able to use the programming languages, tools and operating systems of their choice for their projects – and will still be able to deploy their code on any cloud and any device.

Second, we will accelerate enterprise developers’ use of GitHub, with our direct sales and partner channels and access to Microsoft’s global cloud infrastructure and services.

Finally, we will bring Microsoft’s developer tools and services to new audiences."

**Comment by aethelwulffe** [comment]
What is an Azure?  What is an MS Office?  What is .NET?  Is Visual Studio some sort of IDE?  I remember hacking components out of it back in 2003 to make my own C++ compiler, but that is the last time I took note of such things except when converting .asp stuff to PHP.  We (Open Source communities) were the receiving end of active assault from this company for three decades.

Extraordinary claims require extraordinary evidence.

-Open minds are waiting.

**Comment by marcus-sa** [comment]
https://natfriedman.github.io/hello/

_At the same time, I understand that there is some healthy skepticism in the community, so I wanted to be absolutely clear about two things:_

- _**GitHub will operate independently as a community, platform, and business.** This means that GitHub will retain its developer-first values, distinctive spirit, and open extensibility. We will always support developers in their choice of any language, license, tool, platform, or cloud._

- _**GitHub will retain its product philosophy.** We love GitHub because of the deep care and thoughtfulness that goes into every facet of the developer’s experience. I understand and respect this, and know that we will continue to build tasteful, snappy, polished tools that developers love._

_I’m not asking for your trust, but I’m committed to earning it. I can’t wait to help make the GitHub platform and community that’s special to all of us even greater._
