### ISSUE TITLE
General Issues with the acquisition

### ISSUE THREAD

**Issue by bderiso** [bderiso/Microsoft-Github-acquisition#3]
# Consolidation of Power
Github user GitSquared [nicely articulates some concerns](https://github.com/upend/IF_MS_BUYS_GITHUB_IMMA_OUT/issues/13#issuecomment-394450006) about the sheer amount of control Microsoft will now exert over developers' ability to market themselves and interact with each other.

Specifically, "**Microsoft now owns** (or at least will in a couple of months) **both GitHub and LinkedIn**. That's the services most recruiters use to find developers (particularly freelance)."

**Comment by Gadgetoid** [comment]
I think this may be a valid concern, with some caveats.

I think with a company the size of Microsoft the risk of a power concentration is somewhat mitigated, but I could be wrong. I don't think- as a whole- they are capable of acting competently enough to realise our worst fears.

Also... LinkedIn. Ugh. I can't stand it. I could imagine anything involving LinkedIn/GitHub having any sort of interconnection would be high on my list of fears.

If anything, the trashing of GitHub would present a budding potential employee the opportunity to jump through all the hoops it will take to find, sign up for and contribute to an commercially-backed OSS project on a self-hosted Git instance and maybe get recognised for being one of the few that puts in the effort. Swings and roundabouts, I guess?

I use GitHub for the Hub, not the Git. Many alternatives supply the Git in ample quantities, but are severely lacking in the community aspect, the low friction to Issue/PR submission and the overview that GitHub gives over the wider OSS landscape.

Is there now a power void for a platform that brings the social and networking forces to the wider landscape of Git hosting solutions?

**Comment by bderiso** [comment]
Personally, I think [StackExchange ](https://stackechange.com)offers much better/more-focused networking & job-hunting than LinkedIn, but admittedly they may have a smaller market penetration which yields fewer opportunities even they are higher quality.

Is there a power void now? I'm not convinced.

**Comment by marcus-sa** [comment]
Taken directly from their blog post https://blogs.microsoft.com/blog/2018/06/04/microsoft-github-empowering-developers/:

```
iven all of this, together with GitHub, we see three clear opportunities ahead.

First, we will empower developers at every stage of the development lifecycle – from ideation to collaboration to deployment to the cloud. Going forward, GitHub will remain an open platform, which any developer can plug into and extend. Developers will continue to be able to use the programming languages, tools and operating systems of their choice for their projects – and will still be able to deploy their code on any cloud and any device.

Second, we will accelerate enterprise developers’ use of GitHub, with our direct sales and partner channels and access to Microsoft’s global cloud infrastructure and services.

Finally, we will bring Microsoft’s developer tools and services to new audiences.
```

**Comment by marcus-sa** [comment]
https://natfriedman.github.io/hello/

_At the same time, I understand that there is some healthy skepticism in the community, so I wanted to be absolutely clear about two things:_

- _**GitHub will operate independently as a community, platform, and business.** This means that GitHub will retain its developer-first values, distinctive spirit, and open extensibility. We will always support developers in their choice of any language, license, tool, platform, or cloud._

- _**GitHub will retain its product philosophy.** We love GitHub because of the deep care and thoughtfulness that goes into every facet of the developer’s experience. I understand and respect this, and know that we will continue to build tasteful, snappy, polished tools that developers love._

_I’m not asking for your trust, but I’m committed to earning it. I can’t wait to help make the GitHub platform and community that’s special to all of us even greater._
