### ISSUE TITLE
Microsoft's History

### ISSUE THREAD

**Issue by bderiso** [bderiso/Microsoft-Github-acquisition#4]
# Anti-competitive Behavior
Nobody can plausibly deny that [Microsoft has a history of sordid, monopolistic, and even hostile business practices](https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish), but just as "past performance is no guarantee of future results", neither is past action a good indicator of future behavior, ESPECIALLY considering the very heavy regulation Microsoft was subjected to as punishment for that action (Indeed, one could say they have great motivation to behave differently and altruistically, simply from a marketing perspective).

# Acquisition History
Additionally, Github user aensley [hints at some good points](https://github.com/dear-github/dear-github/issues/302#issue-329047716) about Microsoft's habit of buying and then either abandoning projects or making them arguably worse & less useful.

https://en.wikipedia.org/wiki/List_of_mergers_and_acquisitions_by_Microsoft

**Comment by feat7** [comment]
I think things have changed a lot. With Nadella in power, Microsoft has given all into open source.
Microsoft is currently the most active organization on Github as well.
And I really think a good time has come and with this acquisition, Github will be better than ever.

**Comment by bderiso** [comment]
For the record, I share a feeling of cautious optimism towards Microsoft, but I want to be clear that we haven't forgotten their past misdeeds and we're also aware that another management overhaul could make things go bad again.

I think that Era is done for now though, a company is the sum of the people working for it. It is not some other-worldly evil here to kill the entire idea of open-source. :)

**Comment by HaedHutner** [comment]
I think we're past the era of Stevie "Linux is a cancer" Ballmer. It was during his tenure as CEO that most of the acquisitions with terrible outcomes happened. This includes Skype and Nokia. 

GitHub isn't Satya Nadella's first high profile acquisition, either. We should judge this situation based on how previous ones have gone, such as Mojang and LinkedIn. 

Thus far ( as someone who is quite active in the Minecraft modding scene ), I can tell you that Microsoft, at least as far as I can tell, really haven't done much. They've just allowed Mojang to keep doing their own thing, though obviously I don't know what might be happening behind the scenes.

Perhaps someone else can talk about LinkedIn, since I have no profile there and I don't really have a reference point.
